### ISSUE TITLE
Class loading and segfault on ROOT 6.05/01

### ISSUE THREAD

**Issue by brettviren** [BNLIF/Magnify#1]
I reproduce the loading problem on ROOT 6.05/01

```
$ root -l 'Magnify.C("../../celltree_e-_1.5GeV_30x30deg.root")'
root [0] 
Processing Magnify.C("../../celltree_e-_1.5GeV_30x30deg.root")...
In file included from input_line_9:1:
/home/bviren/projects/wire-cell/Magnify/scripts/./Magnify.C:6:5: error: unknown type name 'GuiController'
    GuiController *gc = new GuiController(
    ^
/home/bviren/projects/wire-cell/Magnify/scripts/./Magnify.C:6:29: error: unknown type name 'GuiController'
    GuiController *gc = new GuiController(
```

If I do these three things I can get the `loadClasses.C` to work:
1.  change `loadClass.C` to contain a function with a name that matches the
   file instead of an anonymous code block
2.  comment out the `ProcessLine()` in `Magnify.C`
3.  include `loadClass.C` on the root command line before `Magnify.C`

I recall similar context/scope issues with loading libraries in ROOT5.  They seem to "sometimes" work.

This gets Magnify further but then reaches a segfault:

```
$ root -l loadClasses.C 'Magnify.C("../celltree_e-_1.5GeV_30x30deg.root")'
root [0] 
Processing loadClasses.C...
Info in <TUnixSystem::ACLiC>: creating shared library /home/bviren/projects/wire-cell/Magnify/scripts/./../event/Waveforms_cc.so
Info in <TUnixSystem::ACLiC>: creating shared library /home/bviren/projects/wire-cell/Magnify/scripts/./../event/Data_cc.so
Info in <TUnixSystem::ACLiC>: creating shared library /home/bviren/projects/wire-cell/Magnify/scripts/./../viewer/ViewWindow_cc.so
Info in <TUnixSystem::ACLiC>: creating shared library /home/bviren/projects/wire-cell/Magnify/scripts/./../viewer/ControlWindow_cc.so
Info in <TUnixSystem::ACLiC>: creating shared library /home/bviren/projects/wire-cell/Magnify/scripts/./../viewer/MainWindow_cc.so
Info in <TUnixSystem::ACLiC>: creating shared library /home/bviren/projects/wire-cell/Magnify/scripts/./../viewer/GuiController_cc.so
Processing Magnify.C("../celltree_e-_1.5GeV_30x30deg.root")...
Error in <TFile::TFile>: file ../celltree_e-_1.5GeV_30x30deg.root does not exist

 *** Break *** segmentation violation
```

GDB tells me:

```
$ gdb --args root.exe -l loadClasses.C 'Magnify.C("../../celltree_e-_1.5GeV_30x30deg.root")'
...
(gdb) r
Starting program: /home/bviren/projects/wire-cell/install/bin/root.exe -l loadClasses.C Magnify.C\(\"../../celltree_e-_1.5GeV_30x30deg.root\"\)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
root [0] 
Processing loadClasses.C...
Processing Magnify.C("../../celltree_e-_1.5GeV_30x30deg.root")...

Program received signal SIGSEGV, Segmentation fault.
0x00007fffeaee4e62 in Waveforms::Waveforms(TH2F*, TString, TString, double) () from /home/bviren/projects/wire-cell/Magnify/event/Waveforms_cc.so
(gdb) where
#0  0x00007fffeaee4e62 in Waveforms::Waveforms(TH2F*, TString, TString, double) ()
   from /home/bviren/projects/wire-cell/Magnify/event/Waveforms_cc.so
#1  0x00007fffe7040e26 in Data::Data(char const*) () from /home/bviren/projects/wire-cell/Magnify/event/Data_cc.so
#2  0x00007fffe67fcb93 in GuiController::GuiController(TGWindow const*, int, int, char const*) ()
   from /home/bviren/projects/wire-cell/Magnify/viewer/GuiController_cc.so
#3  0x00007ffff7e270cd in Magnify(char const*) ()
#4  0x00007ffff7e2704c in __cling_Un1Qu39(void*) ()
#5  0x00007ffff3803cde in cling::Interpreter::RunFunction(clang::FunctionDecl const*, cling::Value*) ()
   from /home/bviren/projects/wire-cell/install/lib/libCling.so
#6  0x00007ffff3809ab1 in cling::Interpreter::EvaluateInternal(std::string const&, cling::CompilationOptions, cling::Value*, cling::Transaction**)
    () from /home/bviren/projects/wire-cell/install/lib/libCling.so
#7  0x00007ffff3809cef in cling::Interpreter::echo(std::string const&, cling::Value*) ()
   from /home/bviren/projects/wire-cell/install/lib/libCling.so
#8  0x00007ffff38b60b9 in cling::MetaSema::actOnxCommand(llvm::StringRef, llvm::StringRef, cling::Value*) ()
   from /home/bviren/projects/wire-cell/install/lib/libCling.so
#9  0x00007ffff38c2411 in cling::MetaParser::isXCommand(cling::MetaSema::ActionResult&, cling::Value*) ()
   from /home/bviren/projects/wire-cell/install/lib/libCling.so
#10 0x00007ffff38c359e in cling::MetaParser::isCommand(cling::MetaSema::ActionResult&, cling::Value*) ()
   from /home/bviren/projects/wire-cell/install/lib/libCling.so
#11 0x00007ffff38af9eb in cling::MetaProcessor::process(char const*, cling::Interpreter::CompilationResult&, cling::Value*) ()
   from /home/bviren/projects/wire-cell/install/lib/libCling.so
#12 0x00007ffff37a97c5 in TCling::ProcessLine(char const*, TInterpreter::EErrorCode*) ()
   from /home/bviren/projects/wire-cell/install/lib/libCling.so
#13 0x00007ffff37833dd in TCling::ProcessLineSynch(char const*, TInterpreter::EErrorCode*) ()
   from /home/bviren/projects/wire-cell/install/lib/libCling.so
#14 0x00007ffff79fa44d in TApplication::ExecuteFile(char const*, int*, bool) () from /home/bviren/projects/wire-cell/install/lib/libCore.so
#15 0x00007ffff79fb457 in TApplication::ProcessLine(char const*, bool, int*) () from /home/bviren/projects/wire-cell/install/lib/libCore.so
#16 0x00007ffff75e07a5 in TRint::ProcessLineNr(char const*, char const*, int*) () from /home/bviren/projects/wire-cell/install/lib/libRint.so
#17 0x00007ffff75e1c97 in TRint::Run(bool) () from /home/bviren/projects/wire-cell/install/lib/libRint.so
#18 0x0000000000401070 in main ()
```

**Comment by czczc** [comment]
Fixed in https://github.com/BNLIF/Magnify/commit/baf5f1c8d82afa0923a3f8ebc324ee13188c6237 following Brett's suggestions.
